# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:

  run:
    runs-on: ubuntu-latest

    env:
      SITE_URL: ${{ secrets.SITE_URL }}
      SITE_RESPONSE_EXPECTED: ${{ secrets.SITE_RESPONSE_EXPECTED }}

      MAIL_TEMPLATE: ${{ secrets.MAIL_TEMPLATE }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        token_format: 'access_token'
        credentials_json: $${{ secrets.GMAIL_CREDENTIALS_JSON }}

    - name: Run
      env:
        GMAIL_TOKEN: ${{steps.auth.outputs.access_token}}
      run: go run main.go
