# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/988811459859/locations/global/workloadIdentityPools/id-pool-notifier/providers/id-pool-provider-notifier'
        service_account: 'svc-acc-notifier@notifier-368303.iam.gserviceaccount.com'

    - name: Run
      env:
        SITE_URL: ${{ secrets.SITE_URL }}
        SITE_RESPONSE_EXPECTED: ${{ secrets.SITE_RESPONSE_EXPECTED }}

        MAIL_TEMPLATE: ${{ secrets.MAIL_TEMPLATE }}
      run: go run main.go
