# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:

  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Checkout + decrypt large secret
      run: |
        ./decrypt_secret.sh
        LONG_SITE_RESPONSE_EXPECTED=$(cat my_secrets.json)
        echo "SITE_RESPONSE_EXPECTED=$LONG_SITE_RESPONSE_EXPECTED" >> $GITHUB_ENV
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run
      env:
        SITE_URL: ${{ secrets.SITE_URL }}
        ## SITE_RESPONSE_EXPECTED: ${{ secrets.SITE_RESPONSE_EXPECTED }}

        MAIL_TEMPLATE: ${{ secrets.MAIL_TEMPLATE }}

        FACEBOOK_API_BASE: https://graph.facebook.com/
        FACEBOOK_API_VERSION: v15.0
        FACEBOOK_API_PAGE_ID: ${{ secrets.FACEBOOK_API_PAGE_ID }}
        FACEBOOK_API_ACCESS_TOKEN: ${{ secrets.FACEBOOK_API_ACCESS_TOKEN }}
        FACEBOOK_API_PSIDS: ${{ secrets.FACEBOOK_API_PSIDS }}
      run: go run main.go
